### ISSUE TITLE
ethny-pynithy?

### ISSUE THREAD

**Issue by matti** [ethernity-cloud/mvp-pox-node#5]
https://github.com/ethernity-cloud/mvp-pox-node/blob/db58f33ae041728680e59c27976376a77b313d45/node/docker/docker-compose-etny-pynithy.yml#L5

where is this?

**Comment by dim3nsi0n32** [comment]
Hi @matti.
Apologies for the late reply. 
The image is downloaded through ipfs on the localhost and then it's used by docker registry.
Please get in touch via Discord if you would like to discuss further.

Thank you!
