### ISSUE TITLE
Error in step "Deploy the node"

### ISSUE THREAD

**Issue by ruDmitry** [ethernity-cloud/mvp-pox-node#8]
Ubuntu 20.04

I follow the instructions step by step.
Step: Deploy the node
command:
sudo ansible-playbook -i localhost, playbook.yml \
  -e "ansible_python_interpreter=/usr/bin/python3"

Error:
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "vagrant up --provider=libvirt", "delta": "0:00:02.055002", "end": "2022-06-05 22:48:03.733717", "msg": "non-zero return code", "rc": 1, "start": "2022-06-05 22:48:01.678715", "stderr": "/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rexml (LoadError)\n\tfrom /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n\tfrom /root/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:4:in `<top (required)>'\n\tfrom /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n\tfrom /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n\tfrom /root/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action.rb:99:in `block (2 levels) in action_up'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/call.rb:47:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/box_check_outdated.rb:92:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/config_validate.rb:25:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:613:in `lock'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `call'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'\n\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'", "stderr_lines": ["/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rexml (LoadError)", "\tfrom /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "\tfrom /root/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:4:in `<top (required)>'", "\tfrom /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "\tfrom /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "\tfrom /root/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action.rb:99:in `block (2 levels) in action_up'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/call.rb:47:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/box_check_outdated.rb:92:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/config_validate.rb:25:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:613:in `lock'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `call'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'", "\tfrom /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'"], "stdout": "Bringing machine 'etnyvm1' up with 'libvirt' provider...\n==> etnyvm1: Checking if box 'generic/ubuntu1804' version '4.0.2' is up to date...", "stdout_lines": ["Bringing machine 'etnyvm1' up with 'libvirt' provider...", "==> etnyvm1: Checking if box 'generic/ubuntu1804' version '4.0.2' is up to date..."]}

**Comment by ruDmitry** [comment]
Reinstall OS (Ubuntu 20.04)
i9-9900K / 8Gb / 60Gb

I follow the instructions step by step.
Step: Deploy the node
command:
sudo ansible-playbook -i localhost, playbook.yml

-e "ansible_python_interpreter=/usr/bin/python3"
Log in attach
[log.txt](https://github.com/ethernity-cloud/mvp-pox-node/files/8840868/log.txt)

**Comment by dim3nsi0n32** [comment]
Dear Dmitry, apologies for the late reply. By looking at the log file I can see that the vagrant did start successfully and it starting updating the virtual machine and somewhere along the update process it stopped. I can only think that there was an issue with the network connection.
Did you manage to install the node in the end?
Can you please get in touch with me via Discord to discuss this further?
Thank you!
